### ISSUE TITLE
FunctionCall requires a primary key

### ISSUE THREAD

**Issue by ogchrislem** [betalgo/openai#346]
**Describe the bug**
Upgrading from 7.0.0 to 7.1.3 the, following error occurs when trying to execute LINQ queries in EFCore (7.0.9)

System.InvalidOperationException: The entity type 'FunctionCall' requires a primary key to be defined. If you intended to use a keyless entity type, call 'HasNoKey' in 'OnModelCreating'. For more information on keyless entity types, see https://go.microsoft.com/fwlink/?linkid=2141943.

**Your code piece**
Error is triggered by any code similar to this, trying to run a LINQ query using EFCore, the return line errors
```
            await using var ctx = await _dbContextFactory.CreateDbContextAsync();
      
            return await ctx.MyDBEntities
                .Where(q => q.UserId == userId)
                .OrderBy(p => p.Name)
                .ToListAsync();
```
**Result**
Stack trace from error line:
```
System.InvalidOperationException: The entity type 'FunctionCall' requires a primary key to be defined. If you intended to use a keyless entity type, call 'HasNoKey' in 'OnModelCreating'. For more information on keyless entity types, see https://go.microsoft.com/fwlink/?linkid=2141943.
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelValidator.ValidateNonNullPrimaryKeys(IModel model, IDiagnosticsLogger`1 logger)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelValidator.Validate(IModel model, IDiagnosticsLogger`1 logger)
   at Microsoft.EntityFrameworkCore.Infrastructure.RelationalModelValidator.Validate(IModel model, IDiagnosticsLogger`1 logger)
   at Microsoft.EntityFrameworkCore.SqlServer.Infrastructure.Internal.SqlServerModelValidator.Validate(IModel model, IDiagnosticsLogger`1 logger)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelRuntimeInitializer.Initialize(IModel model, Boolean designTime, IDiagnosticsLogger`1 validationLogger)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.GetModel(DbContext context, ModelCreationDependencies modelCreationDependencies, Boolean designTime)
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel(Boolean designTime)
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   at Microsoft.EntityFrameworkCore.Infrastructure.EntityFrameworkServicesBuilder.<>c.<TryAddCoreServices>b__8_4(IServiceProvider p)
   at ResolveService(ILEmitResolverBuilderRuntimeContext, ServiceProviderEngineScope)
   at ResolveService(ILEmitResolverBuilderRuntimeContext, ServiceProviderEngineScope)
   at ResolveService(ILEmitResolverBuilderRuntimeContext, ServiceProviderEngineScope)
   at ResolveService(ILEmitResolverBuilderRuntimeContext, ServiceProviderEngineScope)
   at ResolveService(ILEmitResolverBuilderRuntimeContext, ServiceProviderEngineScope)
   at ResolveService(ILEmitResolverBuilderRuntimeContext, ServiceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_ContextServices()
   at Microsoft.EntityFrameworkCore.DbContext.get_Model()
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.get_EntityType()
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.get_EntityQueryable()
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.System.Linq.IQueryable.get_Provider()
   at System.Linq.Queryable.Where[TSource](IQueryable`1 source, Expression`1 predicate)
```

**Expected behavior**
The LINQ query should run without error, worked in 7.0.0

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows Server 2022
 - Language: C#
 - Version 7.1.3

**Additional context**
I guess EFCore has picked up and is trying to validate OpenAI.ObjectModels.RequestModels.FunctionCall, I don't know why or if there is there a way to get it to ignore it

**Comment by kayhantolga** [comment]
Hi, thank you for your report. As a best practice, I recommend using your own models to store data as library models can change over time and potentially cause issues in your database. It is unclear why EF did not recognize the FunctionCall field, but it may be because it is an object without an ID.

My first suggestion is to use your own model to store and retrieve data. If you prefer not to, then Fluent API may be helpful. You can learn more about it here: https://learn.microsoft.com/en-us/ef/ef6/modeling/code-first/fluent/types-and-properties

I am closing this ticket as "not planned." If you disagree, please do not hesitate to reopen it.

**Comment by ogchrislem** [comment]
OK got it, I was inheriting ChatMessage for my DB entity. I've removed the dependency and there are no errors with the latest version now. Thanks for your helpful response and all your work on this project  👍🏻
