### ISSUE TITLE
Function calling does not work with chat response streaming

### ISSUE THREAD

**Issue by dex3r** [betalgo/openai#381]
**Describe the bug**
When using Chat with Functions and Streaming, an JSON parsing exception is thrown:

```c#
System.Text.Json.JsonReaderException: Expected depth to be zero at the end of the JSON payload. There is an open JSON object or array that should be closed. LineNumber: 0 | BytePositionInLine: 1.
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
   at System.Text.Json.Utf8JsonReader.ReadSingleSegment()
   at System.Text.Json.Utf8JsonReader.Read()
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
```

**Your code piece**

```c#
OpenAIService api = GetApi();

request.Stream = true;
IAsyncEnumerable<ChatCompletionCreateResponse> responseStream = api.ChatCompletion.CreateCompletionAsStream(request);

await foreach (ChatCompletionCreateResponse partialResponse in responseStream) //<-- Exception is thrown here
{
	if (!partialResponse.Successful)
	{
		throw new Exception(GetResponseErrorAsString(partialResponse.Error));
	}
	
	LogResponse(partialResponse);
}
```

**Result**
An exception is thrown.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Language C# 10, dotnet 6, 
 - Version 7.1.5

**Comment by dex3r** [comment]
This was a user error: one of the history messages passed to the AI had an empty role field.
