### ISSUE TITLE
Usage is always null when using CreateCompletionAsStream

### ISSUE THREAD

**Issue by igor-topolski** [betalgo/openai#404]
**Describe the bug**

I was trying to get usage information for the prompt created using `CreateCompletionAsStream` - information I am after is tokens consumed on prompt and completion.

When trying to access `completion.Usage.CompletionTokens`, `completion.Usage.PromptTokens` or `completion.Usage.TotalTokens` I get NullReferenceException indicating `Usage` is null. Upon investigation it looks like `Usage` object is always null.

**Your code piece**
```csharp
var completionResult = _openAiService.ChatCompletion.CreateCompletionAsStream(
    new ChatCompletionCreateRequest
    {
        Messages = messages,
        Model = Models.ChatGpt3_5Turbo,
        MaxTokens = 300 //optional
    });

await foreach (var completion in completionResult)
{
    if (completion.Successful)
    {
        Console.WriteLine(completion.Usage.CompletionTokens);
        Console.WriteLine(completion.Usage.PromptTokens);
        Console.WriteLine(completion.Usage.TotalTokens);
    }
    else
    {
        if (completion.Error == null)
        {
            throw new Exception("Unknown Error");
        }

        Console.WriteLine($"{completion.Error.Code}: {completion.Error.Message}");
    }
}
```
**Result**

```
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at AiBook.Worker.ExecuteAsync(CancellationToken stoppingToken) in *******************************/Worker.cs:line 52
   at AiBook.Worker.ExecuteAsync(CancellationToken stoppingToken) in *******************************/Worker.cs:line 48
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Program.<Main>$(String[] args) in *******************************/Program.cs:line 15
   at Program.<Main>(String[] args)
```

Upon serialisation of all of the completions they look pretty much this way
```json
{
  "Model": "gpt-3.5-turbo-0613",
  "Choices": [
    ...
  ],
  "Usage": null,
  "CreatedAt": 1699006980,
  "Id": "chatcmpl-***************************",
  "ObjectTypeName": "chat.completion.chunk",
  "Successful": true,
  "Error": null
}
```
**Expected behaviour**

I believe the Usage should be returned, maybe there's another way of retrieving usage info (tokens consumed) of a particular prompt/completion that I am simply not aware of. Any help would be appreciated :) 

**Desktop (please complete the following information):**
 - OS: MacOS & Windows
 - Language: C# .NET 6 / .NET 8
 - Version: 7.3.1

**Additional context**

**Comment by igor-topolski** [comment]
Actually, it seems to be OpenAI limitation... Closing
