### ISSUE TITLE
Method not found: 'Void OpenAI.Builders.FunctionDefinitionBuilder..ctor(System.String, System.String) on GetToolDefinitions

### ISSUE THREAD

**Issue by WilbertE** [betalgo/openai#649]
**Describe the bug**
I get an error on this line: 
`var tools = FunctionCallingHelper.GetToolDefinitions<[MyClass]>();`
When upgrading Betalgo.OpenAI from 8.6.2 to 8.7.1.
The  Betalgo.OpenAI.Utilities is version 8.1.0

The exception is: `Method not found: 'Void OpenAI.Builders.FunctionDefinitionBuilder..ctor(System.String, System.String)'

The stacktrace is:
```
  at OpenAI.Utilities.FunctionCalling.FunctionCallingHelper.GetFunctionDefinition(MethodInfo methodInfo)
   at OpenAI.Utilities.FunctionCalling.FunctionCallingHelper.GetToolDefinition(MethodInfo methodInfo)
   at OpenAI.Utilities.FunctionCalling.FunctionCallingHelper.<>c.<GetToolDefinitions>b__4_2(<>f__AnonymousType02 t)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator2.ToList()
   at OpenAI.Utilities.FunctionCalling.FunctionCallingHelper.GetToolDefinitions(Type type)
   at OpenAI.Utilities.FunctionCalling.FunctionCallingHelper.GetToolDefinitions[T]()
```

**Comment by aow99** [comment]
Same. Will try reverting back as a work around.
