### ISSUE TITLE
FIne-Tuning request for gpt-4o-2024-08-06, gpt-4o-mini-2024-07-18 and gpt-4-0613

### ISSUE THREAD

**Issue by nappy64** [betalgo/openai#688]
Hi,

..\openai-master\OpenAI.Playground\TestHelpers\FineTuningJobTestHelper.cs
var createFineTuningJobResponse = await sdk.FineTuningJob.CreateFineTuningJob(new()
{
    TrainingFile = uploadFilesResponse.Id,
    Model = Models.Gpt_4o_mini        // from Gpt_3_5_Turbo to Gpt_4o_mini
});

I am trying to add fine-tuning for model Gpt_4o_mini, but got following error message. Do you have any plans to add fine-tuning function for gpt-4o-2024-08-06, gpt-4o-mini-2024-07-18, gpt-4-0613 and further o1 model?

Run Case Study Is The Model Making Untrue Statements:
ft:gpt-3.5-turbo-0125:nc::AbLl9Rrx
ft:gpt-3.5-turbo-0125:nc::AbI8tzQh
Uploading file FineTuningJobSample2.jsonl
FineTuningJobSample2.jsonl uploaded
Wait 5 seconds for the file to be ready
System.Net.Http.HttpRequestException: Response status code does not indicate success: 404 (Not Found).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at System.Net.Http.HttpClient.GetStreamAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at OpenAI.Managers.OpenAIService.ListFineTuningJobEvents(FineTuningJobListEventsRequest fineTuningJobRequestModel, Nullable`1 stream, CancellationToken cancellationToken) in C:\Users\ChNa653\Documents\Projects\AI\openai-master\OpenAI.SDK\Managers\OpenAIFineTuningJob.cs:line 33
   at OpenAI.Playground.TestHelpers.FineTuningJobTestHelper.RunCaseStudyIsTheModelMakingUntrueStatements(IOpenAIService sdk) in C:\Users\ChNa653\Documents\Projects\AI\openai-master\OpenAI.Playground\TestHelpers\FineTuningJobTestHelper.cs:line 48

**Comment by nappy64** [comment]
sorry my bad, I should look into https://platform.openai.com/docs/guides/fine-tuning for more detail, however, since I change the mode to Model = Models.Gpt_4o_mini_2024_07_18, the code completed fine-tune function.

Thanks!

**Comment by nappy64** [comment]
functions existed!
